/* Generated By:JavaCC: Do not edit this line. MiniLengCompilerConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniLengCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tCLASE = 11;
  /** RegularExpression Id. */
  int tMETODO = 12;
  /** RegularExpression Id. */
  int tPROGRAMA = 13;
  /** RegularExpression Id. */
  int tAND = 14;
  /** RegularExpression Id. */
  int tOR = 15;
  /** RegularExpression Id. */
  int tNOT = 16;
  /** RegularExpression Id. */
  int tPRINCIPIO = 17;
  /** RegularExpression Id. */
  int tFIN = 18;
  /** RegularExpression Id. */
  int tSI = 19;
  /** RegularExpression Id. */
  int tENT = 20;
  /** RegularExpression Id. */
  int tSI_NO = 21;
  /** RegularExpression Id. */
  int tFSI = 22;
  /** RegularExpression Id. */
  int tMQ = 23;
  /** RegularExpression Id. */
  int tFMQ = 24;
  /** RegularExpression Id. */
  int tESCRIBIR = 25;
  /** RegularExpression Id. */
  int tLEER = 26;
  /** RegularExpression Id. */
  int tMOD = 27;
  /** RegularExpression Id. */
  int tTRUE = 28;
  /** RegularExpression Id. */
  int tFALSE = 29;
  /** RegularExpression Id. */
  int tENTACAR = 30;
  /** RegularExpression Id. */
  int tCARAENT = 31;
  /** RegularExpression Id. */
  int tACCION = 32;
  /** RegularExpression Id. */
  int tVAL = 33;
  /** RegularExpression Id. */
  int tREF = 34;
  /** RegularExpression Id. */
  int tENTERO = 35;
  /** RegularExpression Id. */
  int tBOOLEANO = 36;
  /** RegularExpression Id. */
  int tCARACTER = 37;
  /** RegularExpression Id. */
  int tIGUAL = 38;
  /** RegularExpression Id. */
  int tFIN_SENTENCIA = 39;
  /** RegularExpression Id. */
  int tMAYOR = 40;
  /** RegularExpression Id. */
  int tMENOR = 41;
  /** RegularExpression Id. */
  int tMAI = 42;
  /** RegularExpression Id. */
  int tMEI = 43;
  /** RegularExpression Id. */
  int tNI = 44;
  /** RegularExpression Id. */
  int tOPAS = 45;
  /** RegularExpression Id. */
  int tMUL = 46;
  /** RegularExpression Id. */
  int tDIV = 47;
  /** RegularExpression Id. */
  int tMAS = 48;
  /** RegularExpression Id. */
  int tMENOS = 49;
  /** RegularExpression Id. */
  int tID = 50;
  /** RegularExpression Id. */
  int tNUM = 51;
  /** RegularExpression Id. */
  int tCAR = 52;
  /** RegularExpression Id. */
  int tCADENA = 53;
  /** RegularExpression Id. */
  int tCifra = 54;
  /** RegularExpression Id. */
  int tLetra = 55;
  /** RegularExpression Id. */
  int tSigno = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIO_MULTILINEA = 1;
  /** Lexical state. */
  int COMENTARIO = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"%\"",
    "\"%%\"",
    "\"%%\"",
    "<token of kind 8>",
    "\"\\n\"",
    "<token of kind 10>",
    "\"clase\"",
    "\"metodo\"",
    "\"programa\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"escribir\"",
    "\"leer\"",
    "\"mod\"",
    "\"true\"",
    "\"false\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\"val\"",
    "\"ref\"",
    "\"entero\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"=\"",
    "\";\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\":=\"",
    "\"*\"",
    "\"div\"",
    "\"+\"",
    "\"-\"",
    "<tID>",
    "<tNUM>",
    "<tCAR>",
    "<tCADENA>",
    "<tCifra>",
    "<tLetra>",
    "<tSigno>",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
